fail_fast: true
repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        types: [python]

      - id: pytest-cov
        name: pytest
        language: system
        entry: pytest --cov="src/main"
        types: [python]